# path to bowtie2 index. Everything before ".1.bt2"
GENOME:
    - "/home/groups/hoolock2/u0/genomes/ucsc/rheMac10/indexes/bowtie2/rheMac10"


# digest file make with the following command: 
# hicup_digester --arima genome.fa 
DIGEST:
    - "/home/groups/hoolock2/u0/genomes/ucsc/rheMac10/hicup-digest/Digest_rheMac10_DpnII_Arima_None_08-47-56_19-01-2020.txt"


CHRSIZES:
    - "/home/groups/hoolock2/u0/genomes/ucsc/rheMac10/rheMac10.chrom.sizes"


ASMBLY:
    - "rheMac10"
    
threads: 10

